---
linters:
  enable-all: true
  disable:
    - execinquery
    - exportloopref
    - gomnd
    - testpackage
linters-settings:
  depguard:
    rules:
      main:
        # List of file globs that will match this list of settings to compare
        # against.
        # Default: $all
        files:
          - "!**/*_a _file.go"
        allow:
          - $gostd
          - github.com/aws/aws-sdk-go-v2/aws
          - github.com/schubergphilis/mcvs-texttidy/internal/app/mcvs-texttidy/application
          - github.com/schubergphilis/mcvs-texttidy/internal/app/mcvs-texttidy/data
          - github.com/schubergphilis/mcvs-texttidy/internal/app/mcvs-texttidy/presentation
          - github.com/sirupsen/logrus
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/require
        deny:
          - pkg: "log"
            desc: Use 'log "github.com/sirupsen/logrus"' instead
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
